# Generated by Django 3.2 on 2021-04-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_typu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení typu jazyku')),
                ('druh', models.CharField(blank=True, choices=[('vyšší', 'vyšší programovací jazyk'), ('nižší', 'nižší programovací jazyk')], default='vyšší', help_text='Vyberte označení druhu programovacího jazyku', max_length=20, verbose_name='Druh')),
            ],
            options={
                'verbose_name': 'Typ jazyku',
                'verbose_name_plural': 'Typy jazyku',
                'ordering': ['oznaceni_typu'],
            },
        ),
        migrations.CreateModel(
            name='Jazyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název jazyku')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis jazyku')),
                ('oblibenost', models.IntegerField(blank=True, choices=[(5, 'naprosto oblíbený'), (4, 'oblíbený'), (3, 'průměr'), (2, 'neoblíbený'), (1, 'ten se ani neuč')], default=3, help_text='Vyberte oblíbenost jazyku', verbose_name='Oblíbenost jazyku')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jazyky/%Y/%m/%d/', verbose_name='Logo jazyku')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='languages.typ')),
            ],
            options={
                'verbose_name': 'Jazyk',
                'verbose_name_plural': 'Jazyky',
                'ordering': ['oblibenost', 'nazev'],
            },
        ),
    ]
